#!/bin/bash
user="sshclip"
home="/var/local/sshclip"
useradd -c "sshclip account" -d "$home" -N -g nogroup -s /usr/local/bin/sshclip-shell "$user"
mkdir -p "$home"
chown "${user}:nogroup" "$home"
chmod 0700 "$home"

echo "Created user '${user}' with home '${home}'"

# vim: set ts=4 sw=4 tw=0 et :
